services:
  - type: web
    name: mini-app-music-player
    env: node
    plan: free
    region: oregon
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: BOT_TOKEN
        sync: false
      - key: PORT
        value: 10000
    autoDeploy: true
